/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import start.App;

class AppTest {
    @Test void appInitialises() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
